### ISSUE TITLE
isrcsubmit does not seem to check for no backends?

### ISSUE THREAD

**Issue by CyberSkull** [JonnyJD/musicbrainz-isrcsubmit#95] opened 2015-01-02 06:04 UTC
I got a series of errors on OS X until I finally (successfully) installed `libdiscid`. So it may be that the script does not check for a "no backends" condition and gracefully exit with an error message.

    isrcsubmit 2.0.0 by JonnyJD for MusicBrainz
    Traceback (most recent call last):
      File "/usr/local/bin/isrcsubmit.py", line 5, in <module>
        pkg_resources.run_script('isrcsubmit==2.0.0', 'isrcsubmit.py')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1357, in run_script
        exec_(script_code, namespace, namespace)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 47, in exec_
        exec("""exec code in globs, locs""")
      File "<string>", line 1, in <module>
      File "/Library/Python/2.7/site-packages/isrcsubmit-2.0.0-py2.7.egg/EGG-INFO/scripts/isrcsubmit.py", line 1122, in <module>
    
      File "/Library/Python/2.7/site-packages/isrcsubmit-2.0.0-py2.7.egg/EGG-INFO/scripts/isrcsubmit.py", line 1055, in main
    
      File "/Library/Python/2.7/site-packages/isrcsubmit-2.0.0-py2.7.egg/EGG-INFO/scripts/isrcsubmit.py", line 286, in gather_options
    
      File "/Library/Python/2.7/site-packages/isrcsubmit-2.0.0-py2.7.egg/EGG-INFO/scripts/isrcsubmit.py", line 372, in find_backend
    
    TypeError

**Comment by JonnyJD** [comment] 2015-01-02 10:24
Thanks a lot for reporting. That is actually a regression in the error handling.

For missing backends you should get this error:
```
ERROR: Cannot find a backend to extract the ISRCS!
       Isrcsubmit can work with one of the following:
         mediatools, media_info, cdrdao, libdiscid, discisrc
```
However, the message fails to display because of an error in listing the possible backends :-/
This should be fixed with #96 (I will make a new release soon).

**Closed** 2015-01-02 10:26 UTC
