### ISSUE TITLE
`setup.py install` broken

### ISSUE THREAD

**Issue by Freso** [JonnyJD/musicbrainz-isrcsubmit#119] opened 2018-08-07 15:46 UTC
`python setup.py build` works and `python setup.py test` works, but `python setup.py install` will bork apparently due to a dependency:
```
> env LANG=C makepkg -fsCi
==> Making package: isrcsubmit-git 2.0.1.r9.gb2d5e24-1 (Tue Aug  7 17:46:07 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating isrcsubmit-git git repo...
Fetching origin
==> Validating source files with md5sums...
    isrcsubmit-git ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of isrcsubmit-git git repo...
Cloning into 'isrcsubmit-git'...
done.
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
running build
running build_scripts
creating build
creating build/scripts-3.7
copying and adjusting isrcsubmit.py -> build/scripts-3.7
changing mode of build/scripts-3.7/isrcsubmit.py from 644 to 755
running build_sphinx_man
creating /tmp/makepkg/isrcsubmit-git/src/isrcsubmit-git/build/doctrees
creating /tmp/makepkg/isrcsubmit-git/src/isrcsubmit-git/build/man
Running Sphinx v1.7.6
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: 2 added, 0 changed, 0 removed
reading sources... [100%] isrcsubmit.1                                                                                     
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... isrcsubmit.1 { } isrcsubmit-config.5 { } 
build succeeded.

The manual pages are in build/man.
==> Starting check()...
running test
test_encoding (test_isrcsubmit.TestInternal) ... ok
test_gather_options (test_isrcsubmit.TestInternal) ... ok
test_cdrdao (test_isrcsubmit.TestScript) ... ok
test_help (test_isrcsubmit.TestScript) ... ok
test_libdiscid (test_isrcsubmit.TestScript) ... ok
test_version (test_isrcsubmit.TestScript) ... ok

----------------------------------------------------------------------
Ran 6 tests in 0.091s

OK
==> Entering fakeroot environment...
==> Starting package()...
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    from isrcsubmit import __version__
  File "/tmp/makepkg/isrcsubmit-git/src/isrcsubmit-git/isrcsubmit.py", line 61, in <module>
    import keyring
  File "/usr/lib/python3.7/site-packages/keyring/__init__.py", line 3, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/lib/python3.7/site-packages/keyring/core.py", line 154, in <module>
    init_backend()
  File "/usr/lib/python3.7/site-packages/keyring/core.py", line 67, in init_backend
    keyrings = filter(limit, backend.get_all_keyring())
  File "/usr/lib/python3.7/site-packages/keyring/util/__init__.py", line 21, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/keyring/backend.py", line 179, in get_all_keyring
    exceptions=TypeError))
  File "/usr/lib/python3.7/site-packages/keyring/util/__init__.py", line 31, in suppress_exceptions
    for callable in callables:
  File "/usr/lib/python3.7/site-packages/keyring/backend.py", line 171, in is_class_viable
    keyring_cls.priority
  File "/usr/lib/python3.7/site-packages/keyring/util/properties.py", line 24, in __get__
    return self.fget.__get__(None, owner)()
  File "/usr/lib/python3.7/site-packages/keyring/backends/SecretService.py", line 37, in priority
    bus = secretstorage.dbus_init()
  File "/usr/lib/python3.7/site-packages/secretstorage/__init__.py", line 41, in dbus_init
    return connect_and_authenticate()
  File "/usr/lib/python3.7/site-packages/jeepney/integrate/blocking.py", line 76, in connect_and_authenticate
    auth_parser.feed(sock.recv(1024))
  File "/usr/lib/python3.7/site-packages/jeepney/auth.py", line 25, in feed
    line, self.buffer = self.buffer.split(b'\r\n', 1)
ValueError: not enough values to unpack (expected 2, got 1)
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by Freso** [comment] 2018-08-07 15:49
I'm thinking this is actually an issue with `keyring` and/or `secretstorage` and/or `jeepny`, just making this issue for tracking it in relation to isrcsubmit.

**Comment by Freso** [comment] 2018-08-07 19:26
Looks like it might be an issue with the fakeroot environment used with `makepkg`, so actually an Arch Linux specific issue; see https://aur.archlinux.org/cgit/aur.git/commit/?h=nagstamon&id=ba289b96c2cd81bad5f04903beae06cc19c16d72 – but it can't just be disabled like that on the PKGBUILD, since we actually do want `keyring` available. I think this may need to be filed at https://bugs.archlinux.org/ and I can't seem to find an existing issue for it.

**Comment by Freso** [comment] 2018-08-08 08:44
Reported issue with `makepkg` for now: https://bugs.archlinux.org/task/59564

**Comment by Xiretza** [comment] 2018-08-08 10:17
The ugly error message can be fixed with this: https://gitlab.com/takluyver/jeepney/merge_requests/4

The root cause though is that a "REJECTED EXTERNAL" is returned, not 100% sure why. The best fix would be to stop importing `keyring` during installation, since merely importing it seems to start up all kinds of backend stuff that's unnecessary and only gets in the way when installing.

**Comment by eli-schwartz** [comment] 2018-08-08 15:27
How do you fix this ugly message:

```
$ pip install --user git+https://github.com/JonnyJD/musicbrainz-isrcsubmit
Collecting git+https://github.com/JonnyJD/musicbrainz-isrcsubmit
  Cloning https://github.com/JonnyJD/musicbrainz-isrcsubmit to /tmp/pip-req-build-gb15km0t
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/tmp/pip-req-build-gb15km0t/isrcsubmit.py", line 47, in <module>
        import discid
    ModuleNotFoundError: No module named 'discid'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-req-build-gb15km0t/isrcsubmit.py", line 51, in <module>
        from libdiscid.compat import discid
    ModuleNotFoundError: No module named 'libdiscid'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-gb15km0t/setup.py", line 13, in <module>
        from isrcsubmit import __version__
      File "/tmp/pip-req-build-gb15km0t/isrcsubmit.py", line 55, in <module>
        import discid
    ModuleNotFoundError: No module named 'discid'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-gb15km0t/
```

Importing the whole *entire* project as a prerequisite to running setup.py seems rqther broken to begin with.

**Comment by Xiretza** [comment] 2018-08-08 18:58
@eli-schwartz: already reported in #116 I guess, for over 2.5 years now.

**Comment by JonnyJD** [comment] 2019-02-05 08:05
@eli-schwartz 
This has *nothing* to do with this problem.
You need to install "python-discid" as a hard requirement for isrcsubmit.

@Xiretza 
No, that ticket was just somebody who expected a Mac installer which installed the dependencies.
Yes, that would be great, but I can't provide that.
And this has *nothing* to do with the problem mentioned here.

Yes, I basically ignored it because I can't spare much maintenance time currently and python-keyring is usually easy to break, difficult to fix, if I can fix anything on this end at all.

**Comment by eli-schwartz** [comment] 2019-02-05 15:38
No, the error message is telling you that even to execute setup.py you need to have preinstalled discid, but pip cannot know that discid is required until after it executes setup.py -- which is a logical circularity and a sign of broken programming. Don't import the version from ircsubmit unless ircsubmit is actually suitable to be imported in setup.py, and while you are at it, don't import the version from ircsubmit if merely importing the freaking version causes you to import keyring too.

Your code does not work according to the Python Packaging Authority. Forget about makepkg.

Your code will continue to be invalid according to the Python Packaging Authority, until https://www.python.org/dev/peps/pep-0518/ achieves broad enough acceptance that you can use pyproject.toml to specify that discid needs to be installed by the "pip" tool or other python package management tools, *before* executing setup.py, and even with pyproject.toml I would argue that the code is still bad even if it is valid, because you have unnecessary frivolous "import keyring" in your setup.py

I'm sorry if you think my attempt to explain to you both the root of your problem and the logical solution, is "rambling" (as per the bugs.archlinux.org ticket). I'll remember next time I have to talk with you, not to bother attempting to provide education. Or just not bother attempting to reach out to community members when they are trying to figure out how to fix makepkg packaging issues.

**Comment by JonnyJD** [comment] 2019-02-10 18:27
This seems to be fixed in python-keyring (or a dependency). I can't reproduce it today.

For the request of improving automatic install of (at least the python) dependencies I opened #121 
The "supported" installation methods are still:
http://jonnyjd.github.io/musicbrainz-isrcsubmit/install

**Closed by JonnyJD** 2019-02-10 18:27 UTC
